export const ON_LOCATION_SELECT = 'ON_LOCATION_SELECT';

export const CURRENT_CONDITIONS_REQUEST = 'CURRENT_CONDITIONS_REQUEST';
export const CURRENT_CONDITIONS_SUCCESS = 'CURRENT_CONDITIONS_SUCCESS';
export const CURRENT_CONDITIONS_FAILED = 'CURRENT_CONDITIONS_FAILED';

export const FORECAST_REQUEST = 'FORECAST_REQUEST';
export const FORECAST_SUCCESS = 'FORECAST_SUCCESS';
export const FORECAST_FAILED = 'FORECAST_FAILED';

export const FORECAST_IMPERIAL = 'FORECAST_IMPERIAL';
export const FORECAST_METRIC = 'FORECAST_METRIC';



