export const LOCATIONS_LIST_REQUEST = 'REQUEST_AUTOCOMPLETE_REQUEST';
export const LOCATIONS_LIST_SUCCESS = 'REQUEST_AUTOCOMPLETE_SUCCESS';
export const LOCATIONS_LIST_FAILED = 'REQUEST_AUTOCOMPLETE_FAILED';
